### ISSUE TITLE
'Open' doesn't work 

### ISSUE THREAD

**Issue by RobertJaskowski** [Neonalig/OneCommander-Connector-for-Unity#1]
While Highlighting it opens the folder and highlights it like expected.

Yet both the 'Open File Dir' and 'Open Folder' only gives window focus to OC, yet doesn't do anything.
Tested also with context menu option, which does the same thing. Only highlighting works.

Unity 2022.2.13
OC 3.42

Keep up the good work!

**Comment by Neonalig** [comment]
Cheers, I'll look into this.
Are you able to send a picture of your current settings just to confirm? (under `Edit>Preferences>OneCommander`)

**Comment by RobertJaskowski** [comment]
![image](https://user-images.githubusercontent.com/32073388/235115634-3853cc57-700b-42d8-8e08-b05efc083d95.png)
I haven't changed any args so if this was required it may be my bad. Yet since the highlight was working I assumed that default ones were good.

**Comment by Neonalig** [comment]
You're absolutely right, the default ones are supposed to be fine. Unfortunately I'm unable to recreate this, and I hate to fallback to "but it works on my system". Can you try swapping the 'Open File Dir Args' and 'Open Folder Args' to use one of the alternate supported argument styles from [OneCommander's CLI Options](https://www.onecommander.com/help/3._Full_reference_guide/Starting_from_Command_line.html)? For example, maybe try:

- Open File Dir Args: `-path "%1-folder"`
- Open Folder Args: `-path "%1"`

Also if you can, enable verbose logging and send a screenshot of the console output. Please also include the folder you expect it to open (i.e. `C:\Some\Folder`) and the folder it actually opens (i.e. `C:\`)

**Comment by RobertJaskowski** [comment]
![image](https://user-images.githubusercontent.com/32073388/235300578-de9c0497-9a2a-4d3b-82f9-1326770fb648.png)
Here I tried 'open' then 'highlight' then 'open'. (Highlight worked)
Used the newer path.
Even when it says "Open from args file to select not set within 1 second. Opening C:\DProjects\GAME\Assets\SuperUnityBuild\Settings" It just gives focus to the OC, yet doesn't actually open.



I also tried the 'alternate supported argument styles' you provided which **worked**.

**Comment by Neonalig** [comment]
So the alternate arguments work? Then moving forwards I'll make that the default in future versions, as theoretically (according to OneCommander documentation anyways) they should all work identically. For reference, what console log system is this? I was expecting Unity's console window, but this provides much more detail.

**Comment by RobertJaskowski** [comment]
Here you go.
`[OneCommander/OpenInOC.OnProjectWindowItemOnGUI] Opening directory in OneCommander: C:\DProjects\GAME\Assets\SuperUnityBuild\Settings
UnityEngine.Debug:Log (object)
OneCommander.OpenInOC:LogVerbose (string,string) (at Assets/Plugins/OneCommander/OpenInOC.cs:48)
OneCommander.OpenInOC:OnProjectWindowItemOnGUI (string,UnityEngine.Rect) (at Assets/Plugins/OneCommander/OpenInOC.cs:190)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`


`[OneCommander/OpenInOC.OpenFolderInOneCommander] Invoking 'C:\Program Files\OneCommander\OneCommander.exe' with arguments: '-"C:\DProjects\GAME\Assets\SuperUnityBuild\Settings"'
UnityEngine.Debug:Log (object)
OneCommander.OpenInOC:LogVerbose (string,string) (at Assets/Plugins/OneCommander/OpenInOC.cs:48)
OneCommander.OpenInOC:RunWithOC (string,string,string) (at Assets/Plugins/OneCommander/OpenInOC.cs:244)
OneCommander.OpenInOC:OpenFolderInOneCommander (System.IO.DirectoryInfo) (at Assets/Plugins/OneCommander/OpenInOC.cs:248)
OneCommander.OpenInOC:OnProjectWindowItemOnGUI (string,UnityEngine.Rect) (at Assets/Plugins/OneCommander/OpenInOC.cs:191)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`


The previous logs were OC's log after turning it on in settings > then %appdata%

**Comment by Neonalig** [comment]
Cheers. Given that you've said the alternate command arguments work, I'll make those the default for the next version. If everything works fine now, then I'm ready to close the issue when you are.
